name: animated_emoji_generator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  mason_logger: ^0.2.10
  recase: ^4.1.0
  dart_animated_emoji: ^0.0.3
  dart_style: ^2.3.3
  args: ^2.4.2
  path: ^1.8.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
